#debug: true
spring:
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://localhost:5432/recime
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
server:
  error:
    include-message: ALWAYS