# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
 version: 2.1

 # Define a job to be invoked later in a workflow.
 # See: https://circleci.com/docs/configuration-reference/#jobs
 jobs:
   build:
     # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
     # See: https://circleci.com/docs/configuration-reference/#executor-job
     docker:
       - image: 'cimg/openjdk:21.0.0'
       - image: 'cimg/postgres:16.0'
         environment:
           POSTGRES_USER: postgres
           POSTGRES_PASSWORD: postgres
           POSTGRES_DB: recime
     # Add steps to the job
     # See: https://circleci.com/docs/configuration-reference/#steps
     steps:
       - checkout
       - run:
           name: "Install Dockerize"
           command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
           environment:
             DOCKERIZE_VERSION: v0.7.0
       - run: sudo apt-get update
       - run:
           name: "Wait for the db"
           command: dockerize -wait tcp://localhost:5432 -timeout 1m
 #      - run: sudo apt-get install postgresql-client   # (optional)
       - run: whoami
       - run:
           name: "Check Java Runtime Environment"
           command: java --version
 #      - run: # (removing due to conflict in bash command)
 #          name: "Postgres Default Setup"
 #          command: docker run --rm --env POSTGRES_USER=${POSTGRES_USER} --env POSTGRES_PASSWORD=${POSTGRES_PASSWORD} -p 5432:5432 -d $IMAGE postgres -c 'config_file=/etc/postgresql/postgresql.conf'
       - run:
           name: "Build Project and Install Dependencies"
           command: |
              ./mvnw clean install
 # Orchestrate jobs using workflows
 # See: https://circleci.com/docs/configuration-reference/#workflows
 workflows:
   build-test-workflow:
     jobs:
       - build

